### ISSUE TITLE
preslavxyz - Discrepancy in `decimals()` function

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-sentiment-v2-judging#10]
preslavxyz

Medium

# Discrepancy in `decimals()` function

## Summary
Discrepancy in `decimals()` function of Chainlink's `AggregatorV3Interface`
## Vulnerability Detail
Both in `ChainlinkEthOracle` and `ChainlinkUsdOracle` contracts an interface called `IAggegregatorV3` (which has a typo) is implented.
```solidity
interface IAggegregatorV3 {
    function latestRoundData()
        external
        view
        returns (uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound);

    function decimals() external view returns (uint256);
}
```
However, as you can see, `decimals` function returns a `uint256` value which is not correct. After some research of the Data Feeds API Reference of `AggregatorV3Interface` in [Chainlink documentation](https://docs.chain.link/data-feeds/api-reference#functions-in-aggregatorv3interface) we can see:
```solidity
function decimals() external view returns (uint8);
```

## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/oracle/ChainlinkEthOracle.sol#L21
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/oracle/ChainlinkUsdOracle.sol#L19
## Tool used
Manual Review
## Recommendation
The new interface should look like this:
```solidity
interface IAggregatorV3 {
    function latestRoundData()
        external
        view
        returns (uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound);

    function decimals() external view returns (uint8);
}
```
Replace in https://github.com/sentimentxyz/protocol-v2/blob/04bf15565165396608cc0aedacf05897235518fd/src/oracle/ChainlinkUsdOracle.sol#L13-L20 and https://github.com/sentimentxyz/protocol-v2/blob/04bf15565165396608cc0aedacf05897235518fd/src/oracle/ChainlinkEthOracle.sol#L15-L22

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sentimentxyz/protocol-v2/pull/316
