### ISSUE TITLE
Flare - Use `safeTransfer` instead of `transfer`

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-sentiment-v2-judging#116]
Flare

Medium

# Use `safeTransfer` instead of `transfer`

## Summary
The ERC20.transfer() function return a boolean value indicating success. This parameter needs to be checked for success. Some tokens do not revert if the transfer failed but return false instead.

## Vulnerability Detail
Some tokens (like USDT) don't correctly implement the EIP20 standard and their transfer/ transferFrom function return void instead of a success boolean. Calling these functions with the correct EIP20 function signatures will always revert.

## Impact
Tokens that don't actually perform the transfer and return false are still counted as a correct transfer and tokens that don't correctly implement the latest EIP20 spec, like USDT, will be unusable in the protocol as they revert the transaction because of the missing return value.

## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/SuperPoolFactory.sol#L76

## Tool used

Manual Review

## Recommendation
Use safeTransfer instead of transfer.

**Comment by blutorque** [comment]
Hey @z3s , in the [readme](https://audits.sherlock.xyz/contests/349?filter=questions) it is confirmed that USDT is a supported token.

**Comment by 0xHacker2684** [comment]
Hey @z3s , in the [readme](https://audits.sherlock.xyz/contests/349?filter=questions) it is confirmed that USDT is a supported token.
