### ISSUE TITLE
X12 - Liquidations on borrowed pool shares may cause bad debt

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-sentiment-v2-judging#119]
X12

High

# Liquidations on borrowed pool shares may cause bad debt

## Summary
When borrowing pool shares, liquidators may not have access to enough shares to repay the debt, leading to bad debt.

## Vulnerability Detail
The system allows pools to use shares as their assets, meaning users can use these shares as collateral and as borrowed assets. However, if shares are used as borrowed assets, the system could accrue bad debt. This is because liquidation needs to happen promptly to avoid bad debt, but this may not be possible when the borrowed assets are pool shares. These shares might have limited liquidity, or the pool might have reached its cap.

Example:
1. Alice has 100 A tokens as collateral and has borrowed 80 shares of a pool that uses B as an asset.
2. Alice's A tokens lose value, and she needs to be liquidated.
3. The liquidator needs to deposit in pool B, get its shares, and repay Alice's debt.
4. However, pool B has reached its cap and isn't accepting more deposits.

In this scenario, Alice's position would cause bad debt to pool B because liquidators can't obtain enough assets to repay the debt and liquidate Alice.

## Impact
Using shares as collateral or as borrowed assets is risky and can lead to bad debt.

## Tool Used
Manual Review

## Recommendation
Implement a mechanic that bypasses pool caps when called by liquidators (or integrate it into the [liquidate](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/PositionManager.sol#L430-L444) function), allowing liquidators to acquire the shares needed to repay the debt.

**Comment by 0x3b33** [comment]
Escalate
The above issue should be considered valid.

The above issue is showing valid and likely scenario where a user cannot get liquidated and in tern is left to be liquidated as bad debt. 

Also the comment doesn't justify it being invalidate
> This is intended. A pool can opt not to lend against such shares

If the pool chose the shares of another pool as an asset, in the event of bad debt the pool cannot choose to opt not to lend against such shares. It's asset is already fixed.

**Comment by sherlock-admin3** [comment]
> Escalate
> The above issue should be considered valid.
> 
> The above issue is showing valid and likely scenario where a user cannot get liquidated and in tern is left to be liquidated as bad debt. 
> 
> Also the comment doesn't justify it being invalidate
> > This is intended. A pool can opt not to lend against such shares
> 
> If the pool chose the shares of another pool as an asset, in the event of bad debt the pool cannot choose to opt not to lend against such shares. It's asset is already fixed.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ruvaag** [comment]
I can confirm this is intended.

z3s's comment is valid. Such a pool that lends these shares can be created, but is ultimately dangerous for lenders to the pool (who deposit to the pool of their own volition) and no one else.

**Comment by cvetanovv** [comment]
The Sponsor's comment confirms that of the Lead Judge that this is the intended design. If someone decides to deposit in such a pool, it will be his responsibility.

Planning to accept the escalation and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x3b33](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/119/#issuecomment-2353363038): rejected
