### ISSUE TITLE
Obsidian - liquidateBadDebt does not sell the collateral instead it just sends it to the owner, this causes a huge loss for lenders

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-sentiment-v2-judging#123]
Obsidian

Medium

# liquidateBadDebt does not sell the collateral instead it just sends it to the owner, this causes a huge loss for lenders

### Summary

When bad debt accumulates, the collateral still has value so the protocol should sell it for the debt token to repay as much debt as possible and then socialising the remaining amongst lenders as bad debt. This is the fair and correct way to do things.

The following bad debt scenario is what should happen:

1. Borrower borrows 90 ETH worth of assets using 100 ETH worth of collateral
2. The price of the collateral drops unexpectedly quickly such that the collateral is now worth 80 ETH, but the loan is wroth 90 ETH so bad debt has accumulated
3. At this point when `liquidateBadDebt` is called the caller will buy the collateral for the debt token at a discounted price, for example repay 75 ETH worth of the debt token to get the collateral worth 80 ETH
4. In the end state the lenders only suffer bad debt of 15 ETH since the rest was paid off by the bad debt liquidator

The issue is that the protocol does not do this, they never sell the collateral instead just send it to the owner. This leads to huge losses for lenders.

This is what the current implementation of `liquidateBadDebt` will do:

1. Borrower borrows 90 ETH worth of assets using 100 ETH worth of collateral
2. The price of the collateral drops unexpectedly quickly such that the collateral is now worth 80 ETH, but the loan is wroth 90 ETH so bad debt has accumulated
3. At this point when `liquidateBadDebt` is called by the owner, it will not sell the collateral instead just send it to the owner
4. In the end state, lenders suffer a 90 ETH worth of bad debt loss

### Root Cause

[liquidateBadDebt()](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/25a0c8aeaddec273c5318540059165696591ecfb/protocol-v2/src/PositionManager.sol#L446) does not sell/exchange the valuable collateral for the debt to re-imbuirse lenders

### Internal pre-conditions

bad debt accumulates

### Impact

Lenders unfairly suffer a huge fund loss, when they could be reimbursed their funds using the collateral that still has a lot of value

### Mitigation

sell the collateral at a discount to repay as much debt as possible then socialise the rest

consider making it a public function and incentivise it so that it will be called in a timely manner

Duplicate of #307

**Comment by 0xjuaan** [comment]
Escalate

This is a duplicate of #307

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This is a duplicate of #307

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
I agree it is a dup of #307.

Planning to accept the escalation and duplicate this issue with #307.

**Comment by WangSecurity** [comment]
Result:
Medium 
Duplicate of #307

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xjuaan](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/123/#issuecomment-2353327601): accepted
