### ISSUE TITLE
Smacaud - Incorrect check in validateBadDebt function

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-sentiment-v2-judging#137]
Smacaud

Medium

# Incorrect check in validateBadDebt function

## Summary

The validateBadDebt functions allows positions where assets equal debt to be classified as not in bad debt. This behavior affects the liquidateBadDebt function, which relies on this validation to determine whether a position should be liquidated.

## Vulnerability Detail

The validateBadDebt function only reverts when totalAssetValue exceeds totalDebtValue depicting no bad debt

`  function validateBadDebt(address position) external view {
       // ......Existing codes.....
        if (totalAssetValue > totalDebtValue) revert RiskModule_NoBadDebt(position);
    }`

However, if totalAssetValue = totalDebtValue, the function does not revert and incorrectly considers the position as being in bad debt. 

This can lead to case where totalAssetValue = totalDebtValue is being considered as bad debt which is technically not. The owner can go ahead to liquidate the position thinking its bad debt because of the incorrect check. 

## Impact

The implementation could lead to unfair liquidations of positions that are technically not in bad debt (case of totalAssetValue = totalDebtValue )

## Code Snippet

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/RiskModule.sol#L126

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/PositionManager.sol#L447

## Tool used

Manual Review

## Recommendation

Adjust the validateBadDebt function to handle the scenario where totalAssetValue is equal to totalDebtValue more accurately.

**Comment by samuraii77** [comment]
Escalate

1 wei difference, it is very low likelihood (pretty much impossible) for this to have an effect in a real scenario, issue should be of low severity.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> 1 wei difference, it is very low likelihood (pretty much impossible) for this to have an effect in a real scenario, issue should be of low severity.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by iamnmt** [comment]
Escalate

Invalid.

Since there is no documentation or no existing code shows that a position with `totalAssetValue = totalDebtValue` is **NOT** a bad debt, it is a design choice to consider such position is a bad debt.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Invalid.
> 
> Since there is no documentation or no existing code shows that a position with `totalAssetValue = totalDebtValue` is **NOT** a bad debt, it is a design choice to consider such position is a bad debt.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ruvaag** [comment]
This should be a low at best. Practically a position with equal debt and collateral is actually still in bad debt, because liquidation costs are > 0

**Comment by cvetanovv** [comment]
I agree with the comments and the escalation.

The sponsor confirms that this is at most Low severity. We don't have any problem here.

Planning to accept the escalation and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [iamnmt](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/137/#issuecomment-2351849191): accepted
