### ISSUE TITLE
zarkk01 - SuperPool not keeping track of what happens in the invested BasePools between ```accrue()``` calls can lead to loss of interest fee shares for the owner.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-sentiment-v2-judging#166]
zarkk01

Medium

# SuperPool not keeping track of what happens in the invested BasePools between ```accrue()``` calls can lead to loss of interest fee shares for the owner.

## Summary
```accrue()``` function in SuperPool fails to account correctly for changes in invested BasePools, leading to missed fee share minting for the owner when interest accrues but is "offset" by losses in other(s) BasePool(s).

## Vulnerability Detail
Every ```SuperPool``` keeps track of the ```totalAssets```it controls using the ```accrue()``` function which is called before every action. This fuction checks if there is any interest accrued from the BasePools and mints the corresponding fee shares for the owner of the ```SuperPool```. We can see the implementation of this function here :

```solidity
    function accrue() public {
        (uint256 feeShares, uint256 newTotalAssets) = simulateAccrue();
        if (feeShares != 0) ERC20._mint(feeRecipient, feeShares);
        lastTotalAssets = newTotalAssets;
    }

    function simulateAccrue() internal view returns (uint256, uint256) {
        uint256 newTotalAssets = totalAssets();
        uint256 interestAccrued = (newTotalAssets > lastTotalAssets) ? newTotalAssets - lastTotalAssets : 0;
        if (interestAccrued == 0 || fee == 0) return (0, newTotalAssets);

        uint256 feeAssets = interestAccrued.mulDiv(fee, WAD);
        // newTotalAssets already includes feeAssets
        uint256 feeShares = _convertToShares(feeAssets, newTotalAssets - feeAssets, totalSupply(), Math.Rounding.Down);

        return (feeShares, newTotalAssets);
    }
```
[Link to code](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/SuperPool.sol#L653C5-L662C19)

However, due to the fact that the ```accrue()``` doesn't synchronize with the changes in BasePools, it is possible that it will think that no interest accrued was generated from the pools and no fee shares will be minted for the owner while this is not the case.

To understand better this vulnerability, let's consider this scenario :

1. SuperPool has 3 BasePools [Basepool A, Basepool B, Basepool C].
2. ```accrue()``` is called and it has the corresponding assets in them [1000 USDC, 2000 USDC, 3000 USDC].
3. Time passes and B and C generate interest as usual, let's say 100 USDC and 200 USDC respectively.
4. In the same time (and with ```accrue()``` not be called since no action happened in SuperPool), Basepool A faces a rebalancing of bad debt and the assets of our SuperPool goes -300 USDC.
5. Finally, ```accrue()``` is called and now it sees this assets [700 USDC, 2100 USDC, 3300 USDC].

Since the totalAmount of assets is the same, it thinks that no interest was generated and no fee shares are minted for the owner. However, this is not the case since the BasePools generated interest as we saw, and the owner shouldn't be penalized for the loss of assets in the BasePool A.

## Code Snippet
Here is the ```accrue``` function flow of ```SuperPool``` contract which doesn't fully synchronize with changes in invested ```Basepools``` :
```solidity
    function accrue() public {
        (uint256 feeShares, uint256 newTotalAssets) = simulateAccrue();
        if (feeShares != 0) ERC20._mint(feeRecipient, feeShares);
        lastTotalAssets = newTotalAssets;
    }

    function simulateAccrue() internal view returns (uint256, uint256) {
        uint256 newTotalAssets = totalAssets();
        uint256 interestAccrued = (newTotalAssets > lastTotalAssets) ? newTotalAssets - lastTotalAssets : 0;
        if (interestAccrued == 0 || fee == 0) return (0, newTotalAssets);

        uint256 feeAssets = interestAccrued.mulDiv(fee, WAD);
        // newTotalAssets already includes feeAssets
        uint256 feeShares = _convertToShares(feeAssets, newTotalAssets - feeAssets, totalSupply(), Math.Rounding.Down);

        return (feeShares, newTotalAssets);
    }

   function totalAssets() public view returns (uint256) {
        uint256 assets = ASSET.balanceOf(address(this));

        uint256 depositQueueLength = depositQueue.length;
        for (uint256 i; i < depositQueueLength; ++i) {
@>            assets += POOL.getAssetsOf(depositQueue[i], address(this));
        }

        return assets;
    }
```

## Tool used
Manual Review

## Recommendation
Consider synchronizing the ```accrue()``` function with the changes in the invested BasePools, maybe with an off chain mechanism.

**Comment by zarkk01** [comment]
Escalate 

```SuperPool.totalAssets``` handles that situation **if** it get called. But if there is interest accrual **and** bad debt liquidation between two calls on ```SuperPool.totalAssets```, then the interest fee shares will be lost for the super pool owner.

**Comment by sherlock-admin3** [comment]
> Escalate 
> 
> ```SuperPool.totalAssets``` handles that situation **if** it get called. But if there is interest accrual **and** bad debt liquidation between two calls on ```SuperPool.totalAssets```, then the interest fee shares will be lost for the super pool owner.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
This is a design decision by the protocol. The `accrue()` function is public, and anyone can call it. That means it can be called even without an action in SuperPool and update the interest. 
Also, the protocol will use bots that can call the function or other functions in SuperPool to update the state.

Planning to reject the escalation and leave the issue as is.

**Comment by zarkk01** [comment]
Hey, thanks for your response! The function is indeed public but this doesn't means that it will be called in time so the fee shares to not be lost. And, in any case, I believe that protocol should not rely on the fact that someone **may** call it (or may not) in time while they can avoid it. Also, this kind of bot is not written in the off chain mechanisms provided from the sponsors. Thanks again but I believe that the protocol must assure that the right and fair fees will not be lost. It can not be a design decision that the fair and **generated** fees from a Pool will be lost because another Pool suffered a bad debt.

**Comment by cvetanovv** [comment]
This is how most protocols work. The `accrue()` function is public, and anyone can call it. It is also called whenever an important action is performed in the contract. 

My decision to reject escalation remains.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [zarkk01](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/166/#issuecomment-2356443906): rejected
