### ISSUE TITLE
X12 - Price feeds will always check the sequencer even if they are on L1

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-sentiment-v2-judging#174]
X12

Medium

# Price feeds will always check the sequencer even if they are on L1

## Summary
Price feeds will always check the sequencer even if they are on L1. This will cause TX to revert.

## Vulnerability Detail
Oracles don't differentiate between base layers and L2s. They check if the sequencer is active no matter what.

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/oracle/ChainlinkEthOracle.sol#L67-L72
```solidity
    function getValueInEth(address asset, uint256 amt) external view returns (uint256) {
        _checkSequencerFeed();

        uint256 ethUsdPrice = _getPriceWithSanityChecks(ETH);
        uint256 assetUsdPrice = _getPriceWithSanityChecks(asset);

        uint256 decimals = IERC20Metadata(asset).decimals();

        if (decimals <= 18) return (amt * 10 ** (18 - decimals)).mulDiv(uint256(assetUsdPrice), uint256(ethUsdPrice));
        else return (amt / (10 ** decimals - 18)).mulDiv(uint256(assetUsdPrice), uint256(ethUsdPrice));
    }
```

However there are no sequencers on L1. TH=he only option is to put a regular price feed on this place, but this will also revert since we are checking `startedAt` and this value represents the last price update (aka. heartbeat), which can be up to 24h.

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/oracle/ChainlinkEthOracle.sol#L87-L96
```solidity
    function _checkSequencerFeed() private view {
        (, int256 answer, uint256 startedAt,,) = ARB_SEQ_FEED.latestRoundData();

        if (answer != 0) revert ChainlinkUsdOracle_SequencerDown();
        if (startedAt == 0) revert ChainlinkUsdOracle_InvalidRound();

        if (block.timestamp - startedAt <= SEQ_GRACE_PERIOD) revert ChainlinkUsdOracle_GracePeriodNotOver();
    }
```
Because of this TX checking the sequencer on L1s will revert.

## Impact
TX using the price feeds on L1s will revert.

## Code Snippet
```solidity
    function _checkSequencerFeed() private view {
        (, int256 answer, uint256 startedAt,,) = ARB_SEQ_FEED.latestRoundData();

        if (answer != 0) revert ChainlinkUsdOracle_SequencerDown();
        if (startedAt == 0) revert ChainlinkUsdOracle_InvalidRound();

        if (block.timestamp - startedAt <= SEQ_GRACE_PERIOD) revert ChainlinkUsdOracle_GracePeriodNotOver();
    }
```
## Tool used
Manual Review

## Recommendation
Add an `if` to verify we are on L2 and call the SEQ, else skip it.

```diff
-    constructor(...) Ownable() {
+    constructor(... , bool _isL2) Ownable() {
+        isL2 = _isL2;

    function getValueInEth(address asset, uint256 amt) external view returns (uint256) {
-       _checkSequencerFeed();
+       if (isL2) _checkSequencerFeed();
```

**Comment by 0x3b33** [comment]
Escalate 

This issue should be valid. The statement bellow doesn't justify the issue being invalidated.
> The Oracles are written with particular L2s. it'd discussed on discord too.

Sherlock also doesn't take discord DMs as a source of truth.
> Discord messages or DM screenshots are not considered sources of truth while judging an issue/escalation especially if they are conflicting with the contest README.

The above issue clearly states that the oracles will not work as intended and will revert on L1s.  These contracts were the only ones we were provided, meaning that by the defined scope and code they are the ones that the system will use when being deployed on every network, be it an L2 or an L1.

**Comment by sherlock-admin3** [comment]
> Escalate 
> 
> This issue should be valid. The statement bellow doesn't justify the issue being invalidated.
> > The Oracles are written with particular L2s. it'd discussed on discord too.
> 
> Sherlock also doesn't take discord DMs as a source of truth.
> > Discord messages or DM screenshots are not considered sources of truth while judging an issue/escalation especially if they are conflicting with the contest README.
> 
> The above issue clearly states that the oracles will not work as intended and will revert on L1s.  These contracts were the only ones we were provided, meaning that by the defined scope and code they are the ones that the system will use when being deployed on every network, be it an L2 or an L1.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
Discord messages or DM screenshots are not sources of truth, but they can be taken into account to complete the whole picture of whether an issue is valid without having much weight. That is only if they don't conflict with the readme.

> screenshots are not considered sources of truth while judging an issue/escalation **especially if they are conflicting with the contest README.**


Also in [sub-point 10](https://docs.sherlock.xyz/audits/judging/judging#iii.-sherlocks-standards), we see the following:
>Watsons are expected to keep up to date with the contest's Discord channel as important announcements impacting judging may arise. **They should keep in mind that any message the Sponsor sends will be considered a source of truth.**

The Readme also states that the protocol is only interested in sequencer issues if they lead to loss of funds. That is not the case in this issue.

>If the codebase is to be deployed on an L2, what should be the behavior of the protocol in case of sequencer issues (if applicable)?
> -  Issues due to sequencer going offline are valid only if they lead to a loss of funds and are not connected to price change risks.

Planning to reject the escalation and leave the issue as is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x3b33](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/174/#issuecomment-2353333829): rejected
