### ISSUE TITLE
X12 - Pool owners cannot remove collateral assets

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-sentiment-v2-judging#177]
X12

Medium

# Pool owners cannot remove collateral assets

## Summary
Pool owners may need to reset/remove the LTV for some collateral assets, however that will be impossible, since the system prevent setting the LTV to 0. This can lead to potentially too risky assets being used as collateral.

## Vulnerability Detail
Pool owners can set LTVs for assets they want to use as collateral against their pool asset (aka. borrowing token). This is done by setting a LTV for that asset using [requestLtvUpdate](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/RiskEngine.sol#L167-L187) and [acceptLtvUpdate](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/RiskEngine.sol#L167-L187).

```solidity
    function requestLtvUpdate(uint256 poolId, address asset, uint256 ltv) external {
        if (msg.sender != pool.ownerOf(poolId)) revert RiskEngine_OnlyPoolOwner(poolId, msg.sender);
        if (oracleFor[asset] == address(0)) revert RiskEngine_NoOracleFound(asset);

        if (ltv < minLtv || ltv > maxLtv) revert RiskEngine_LtvLimitBreached(ltv);
        if (pool.getPoolAssetFor(poolId) == asset) revert RiskEngine_CannotBorrowPoolAsset(poolId);

        LtvUpdate memory ltvUpdate;
        if (ltvFor[poolId][asset] == 0) ltvUpdate = LtvUpdate({ ltv: ltv, validAfter: block.timestamp });
        else ltvUpdate = LtvUpdate({ ltv: ltv, validAfter: block.timestamp + TIMELOCK_DURATION });

        ltvUpdateFor[poolId][asset] = ltvUpdate;
        emit LtvUpdateRequested(poolId, asset, ltvUpdate);
    }
```

However once the asset is set, there is no way to remove it, even if the pool owner and his LPs don't want this asset used as collateral anymore. 

Example:
1. Pool owner adds a new quite risky asset, but sets his LTV at 20%
2. The pool works fine for some time, but that asset is too risky and accrues some bad debt, even at that low LTV

The pool owner has no way to remove it. His only option is to set it to the min LTV at 10%, however that will not make much of a difference.

## Impact
Loss of funds for LPs.

## Code Snippet
```solidity
    function requestLtvUpdate(uint256 poolId, address asset, uint256 ltv) external {
        if (msg.sender != pool.ownerOf(poolId)) revert RiskEngine_OnlyPoolOwner(poolId, msg.sender);
        if (oracleFor[asset] == address(0)) revert RiskEngine_NoOracleFound(asset);

        if (ltv < minLtv || ltv > maxLtv) revert RiskEngine_LtvLimitBreached(ltv);
        if (pool.getPoolAssetFor(poolId) == asset) revert RiskEngine_CannotBorrowPoolAsset(poolId);

        LtvUpdate memory ltvUpdate;
        if (ltvFor[poolId][asset] == 0) ltvUpdate = LtvUpdate({ ltv: ltv, validAfter: block.timestamp });
        else ltvUpdate = LtvUpdate({ ltv: ltv, validAfter: block.timestamp + TIMELOCK_DURATION });

        ltvUpdateFor[poolId][asset] = ltvUpdate;
        emit LtvUpdateRequested(poolId, asset, ltvUpdate);
    }
```
## Tool used
Manual Review

## Recommendation
A good suggestion can be to make a separate map for assets that can be used to open new positions or borrow more. This way risky assets are not gonna be used for borrowing anymore, but old positions which still have them will not be liquidated in an instant.

**Comment by 0x3b33** [comment]
Escalate
This statement has nothing to do with the issue.
> Current design disallows setting LTV to zero, so design decision

The issue above explains how if an asset needs to be removed, it can't. This is dangerous as some assets may change their risk, or the pool it's risk tolerance.

The issue also provides a really good fix suggestion. Just disable borrowing and collateral for the removed asset, which will lower the risk and prevent new and more exposures to it.

Final note: the sponsor will fix this issue, meaning it's not a design decision.

**Comment by sherlock-admin3** [comment]
> Escalate
> This statement has nothing to do with the issue.
> > Current design disallows setting LTV to zero, so design decision
> 
> The issue above explains how if an asset needs to be removed, it can't. This is dangerous as some assets may change their risk, or the pool it's risk tolerance.
> 
> The issue also provides a really good fix suggestion. Just disable borrowing and collateral for the removed asset, which will lower the risk and prevent new and more exposures to it.
> 
> Final note: the sponsor will fix this issue, meaning it's not a design decision.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
@0x3b33 The sponsor's opinion is that the current design does not allow setting the LTV to zero, but they plan to add virtual mapping for smoother onboarding.

**Comment by 0x3b33** [comment]
I don't understand what they mean by
> virtual mapping for smoother onboarding

Are they implementing the recommendation provided by the report ? If they plan to fix this bug, or make it easier for users to navigate around this issue then the finding can be reconsidered as valid.

**Comment by cvetanovv** [comment]
I don't have an answer as to if the protocol will take the recommendation from this issue. 
However, this issue is invalid because it is a future integration issue, and the protocol is not interested in that. In the Readme, we can see:

>Should potential issues, like broken assumptions about function behavior, be reported if they could pose risks in future integrations, even if they might not be an issue in the context of the scope? If yes, can you elaborate on properties/invariants that should hold?
> - No

Planning to reject the escalation and leave the issue as is.

**Comment by 0x3b33** [comment]
Hey @cvetanovv the argument that was provided is not correlated to the issue 

> Should potential issues, like broken assumptions about function behavior, be reported if they could pose risks in future integrations, even if they might not be an issue in the context of the scope? If yes, can you elaborate on properties/invariants that should hold?
> - No

This issue is not about future integrations or alike. But it's about the inability to remove pools, **even if they pose a risk to the system.**

Note that this is also not about `setting LTV to zero`, but for preventing users (that do not currently use them) from using them, as this will increase the overall risk inside the system.

**Comment by 0x3b33** [comment]
Well, the issue is on the edge between issue and a recommendation and given the feedback from the sponsor we can say it's closer to low than a medium.

**Comment by cvetanovv** [comment]
I'm glad we came to the conclusion that this issue is a design recommendation/low severity rather than a medium.

I will reject the escalation.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x3b33](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/177/#issuecomment-2353320137): rejected
