### ISSUE TITLE
almurhasan - Users can’t withdraw/transfer position’s debt tokens in a specific scenario.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-sentiment-v2-judging#214]
almurhasan

Medium

# Users can’t withdraw/transfer position’s debt tokens in a specific scenario.

## Summary
When a new pool is created with an asset, there is no check that the asset must be supported by the PositionManager contract. The PositionManager owner can make an asset  unknown(Before this asset was known) in PositionManager contract , but there is no way to remove the oracle address from an asset in the RiskEngine contract. as a result,users can’t withdraw/transfer those borrowed assets(which is not supported by PositionManager)  from the position .  

## Vulnerability Detail
Users can only withdraw/transfer position’s tokens if the tokens are  KnownAsset by PositionManager( PositionManager’s owner can set known asset by calling the function toggleKnownAsset)

RiskEngine contract’s owner can Set the oracle address used to price for an asset.now one can create pool with those assets(which are set in RiskEngine contract).lender will deposit those assets in those pools and the borrower/position will borrow those assets from those pools.the borrowed asset will be transferred to the position. Now the position owner can withdraw those borrowed assets from the position by executing the  function transfer(PositionManager contract).

Here the bug is if the  PositionManager contract doesn't support any borrowed assets(but pools are created with those assets),then users can’t withdraw/transfer those borrowed assets from the position.  

This can happen in two cases:

1. PositionManager’s  owner can make an asset known or unknown by calling the function toggleKnownAsset in the PositionManager contract . Now if the PositionManager owner can make an asset  unknown(Before this asset was known), then this asset’s  oracle address should also be  removed from the RiskEngine contract. If this asset’s  oracle address is not removed , then pools can be created with this asset, lender will deposit this asset, borrower will borrow this asset but borrower will not be able to withdraw this asset as the asset is not supported by the  PositionManager contract. Here the bug is there is no way to remove the oracle address from an asset in the RiskEngine contract.
 
2. When a new pool is created with an asset, there is no check that the asset must be supported by the PositionManager contract. There is only check that the oracle address must exist for the asset in the RiskEngine contract.so PositionManager contract’s  owner must set those assets as known which has an oracle address in   the RiskEngine contract.if any asset which is supported by RiskEngine contract , but not supported by PositionManager contract, in this situation if users borrows that token , then users can’t withdraw that asset from the position.
## Impact
Users can’t withdraw/transfer position’s debt tokens in a specific scenario.

## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/PositionManager.sol#L316
## Tool used

Manual Review

## Recommendation
When a new pool is created with an asset, check that the asset must be supported by the PositionManager contract. Create a function  to remove the oracle address from an asset in the RiskEngine contract.

Duplicate of #71

**Comment by Almur100** [comment]
This is not duplicate of #71
