### ISSUE TITLE
NoOne - INCOMPATIBILITY WITH NON-STANDARD `ERC20` TOKENS

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-sentiment-v2-judging#236]
NoOne

Medium

# INCOMPATIBILITY WITH NON-STANDARD `ERC20` TOKENS

## Summary
Some tokens (like `USDT`) don’t correctly implement the `EIP20` standard
and their `transfer/transferFrom`  functions return void, instead of a
success boolean. Calling these functions with the correct `EIP20` function
signatures will always revert as it is done in the contract [SuperPoolFactory.sol.::deploySuperPool](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/SuperPoolFactory.sol#L56). Also the `approve` function with `USDT` tokens require resetting the `approva`l to `0` first before being able to reset it to another value.

## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/SuperPoolFactory.sol#L73-L76
## Tool used

Manual Review

## Recommendation

It is recommended to use SafeERC20: `safeTransfer` and to set the `allowance` to zero before increasing the allowance and use `safeApprove/safeIncreaseAllowance`.

Duplicate of #48

**Comment by ruvaag** [comment]
This should be a low. The `approve` is on SuperPool which is an OZ ERC4626. It does not have the same issue as USDT
