### ISSUE TITLE
tedox - Protocol does not account for tokens with different decimals (USDC)

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-sentiment-v2-judging#239]
tedox

Medium

# Protocol does not account for tokens with different decimals (USDC)

## Summary

In the README it is specified that USDC will be used but it has 6 decimals unlike other standard ERC20 tokens which have 18 decimals. The code assumes that all tokens will have 18 decimals which will lead to wrong calculations and unfair liquidations.

## Vulnerability Detail

In `RiskModule::_getPositionAssetData` the weight of each asset is calculated and then it is required that the debt is backed proportionally:
```solidity
                // debt is weighted in proportion to value of position assets. if your position
                // consists of 60% A and 40% B, then 60% of the debt is assigned to be backed by A
                // and 40% by B. this is iteratively computed for each pool the position borrows from
```

But if we take a look at how the weight is calculated:

```solidity
    function _getPositionAssetData(address position)
        internal
        view
        returns (uint256, address[] memory, uint256[] memory)
    {
        uint256 totalAssetValue;

        address[] memory positionAssets = Position(payable(position)).getPositionAssets();
        uint256 positionAssetsLength = positionAssets.length;
        uint256[] memory positionAssetData = new uint256[](positionAssetsLength);

        for (uint256 i; i < positionAssetsLength; ++i) {
            uint256 assets = getAssetValue(position, positionAssets[i]);
            // positionAssetData[i] stores value of positionAssets[i] in eth
            positionAssetData[i] = assets;
            totalAssetValue += assets;
        }

        if (totalAssetValue == 0) return (0, positionAssets, positionAssetData);

        for (uint256 i; i < positionAssetsLength; ++i) {
            // positionAssetData[i] stores weight of positionAsset[i]
            // wt of positionAsset[i] = (value of positionAsset[i]) / (total position assets value)
@>          positionAssetData[i] = positionAssetData[i].mulDiv(1e18, totalAssetValue);
        }

        return (totalAssetValue, positionAssets, positionAssetData);
    }
```

`totalAssetValue` will have 18 decimals if they have deposited any other asset apart from USDC but `positionAssetData[i]` will have 6 decimals when talking about USDC. Because of that the contract will require that an extremely small part of the loan to be covered by USDC even if USDC is the biggest in actual value which will lead to unfair liquidations.

## Impact

Unfair liquidations and wrong calculations in the protocol when USDC is involved.

## Code Snippet

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/RiskModule.sol#L221-L248

## Tool used

Manual Review

## Recommendation

Multiply USDC by e12 in order to match it to other 18 decimals tokens.

**Comment by Pastedko** [comment]
Escalate

I do not se e a reason why this issue is deemed invalid as if the prerequisites provided have happened (which is not at all unlikely) the mentioned impact will occur. There are tokens which have been whitelisted as per the README that have less than 18 decimals (USDC which has 6)

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> I do not se e a reason why this issue is deemed invalid as if the prerequisites provided have happened (which is not at all unlikely) the mentioned impact will occur. There are tokens which have been whitelisted as per the README that have less than 18 decimals (USDC which has 6)

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
The function is working correctly. I guess the Lead Judge invalidated the report because it was unclear and not valid.

You gave the example of the **INTERNAL VIEW** function, which in itself does nothing. You didn't explain any attack path. For example, which function calls this function? For what it is used for. What would be the consequences, etc? As written, it is invalid.

Planning to reject the escalation and leave the issue as is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [pastedko](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/239/#issuecomment-2352895409): rejected
