### ISSUE TITLE
pseudoArtist - `SuperPool` is ERC-4626 compliant, but the `maxWithdraw` & `maxRedeem` functions are not fully up to EIP-4626's specification

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-sentiment-v2-judging#246]
pseudoArtist

Medium

# `SuperPool` is ERC-4626 compliant, but the `maxWithdraw` & `maxRedeem` functions are not fully up to EIP-4626's specification

## Summary
The `maxWithdraw` & `maxRedeem` functions should return the `0` when the withdrawal is `paused`, but in this case it is not returning 0.
## Vulnerability Detail
SuperPool can be paused, since it is pausable contract and also there is a function `togglePause()` , also in the readMe it is specifically written that `superPool` is supposed to be strictly ERC4626 compliant, i.e any issue arising from non compliance should be taken into account and will be a valid issue in this case.

According to [EIP-4626 specifications](https://eips.ethereum.org/EIPS/eip-4626):

`maxWithdraw`
```solidity
MUST factor in both global and user-specific limits, like if withdrawals are entirely disabled (even temporarily) it MUST
 return 0.
 ```
 `maxRedeem`
 
 ```solidity
MUST factor in both global and user-specific limits, like if redemption is entirely disabled (even temporarily) it MUST
 return 0.
 ```

But it is not enforced in our case and the `maxWithdraw` and `maxRedeem` functions are not having any logic to return 0 when to whole contract is paused and withdraw and redeem is disabled in that case.
## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/SuperPool.sol#L220-L223

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/SuperPool.sol#L226-L232
## Tool used

Manual Review

## Recommendation
Include a logic for returning 0 when the contract is paused.

Duplicate of #110

**Comment by zarkk01** [comment]
Escalate 

The EIP-4626, as mentioned in the issue, says :

> like if withdrawals are entirely disabled (even temporarily) it MUST
 return 0.
 
 However, the withdrawals in the current implementation of ```SuperPool``` can **never** be disabled (or any other action) since no action has a modifier for the pausability. So, in the current implementation and since the actions can not be disabled, there is no need to return 0 and ```maxWithdraw``` and ```maxRedeem``` **always** return the right and ERC-4626 compliant price.

**Comment by sherlock-admin3** [comment]
> Escalate 
> 
> The EIP-4626, as mentioned in the issue, says :
> 
> > like if withdrawals are entirely disabled (even temporarily) it MUST
>  return 0.
>  
>  However, the withdrawals in the current implementation of ```SuperPool``` can **never** be disabled (or any other action) since no action has a modifier for the pausability. So, in the current implementation and since the actions can not be disabled, there is no need to return 0 and ```maxWithdraw``` and ```maxRedeem``` **always** return the right and ERC-4626 compliant price.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by PseudoArtistHacks** [comment]
@zarkk01 can you please look at the issue no #270 which quotes that `None of the functions in SuperPool checks pause state` and also look at the superPool [SuperPool.sol#L25](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/SuperPool.sol#L25):

```solidity
contract SuperPool is Ownable, Pausable, ReentrancyGuard, ERC20 {
```

which suggests that superPool is a pausable contract and also there is a function `togglePause()` :

```solidity
    /// @notice Toggle pause state of the SuperPool
    function togglePause() external onlyOwner {
        if (Pausable.paused()) Pausable._unpause();
        else Pausable._pause();
    }
```

Which clearly indicates the whole contract is pausable and in that case deposit as well as withdraw will not be enabled and so the compliance to ERC4626 is an issue in this case.

**Comment by cvetanovv** [comment]
This issue is valid and will be a duplicate of #110. You can see this comment: https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/110#issuecomment-2361832167

Planning to reject the escalation because it will remain valid, but I will duplicate it with #110

**Comment by WangSecurity** [comment]
Result:
Medium
Duplicate of #110

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [zarkk01](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/246/#issuecomment-2352184888): rejected

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sentimentxyz/protocol-v2/pull/342
