### ISSUE TITLE
000000 - `Pool` contract doesn't strictly follow EIP6909

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-sentiment-v2-judging#274]
000000

Medium

# `Pool` contract doesn't strictly follow EIP6909

## Summary
`Pool` contract doesn't strictly follow EIP6909
## Vulnerability Detail
As noted in the contest README, the `Pool` contract should strictly follow EIP6909. As seen in the ERC-6909 standard (https://eips.ethereum.org/EIPS/eip-6909#events), the `Transfer` event should have the following parameters:
>  inputs:
    - name: caller
      indexed: false
      type: address
    - name: sender
      indexed: true
      type: address
    - name: receiver
      indexed: true
      type: address
    - name: id
      indexed: true
      type: uint256
    - name: amount
      indexed: false
      type: uint256

Let's take a look at the `Transfer` event in `ERC6909`:
```solidity
event Transfer(address caller, address indexed from, address indexed to, uint256 indexed id, uint256 amount);
```
As seen the second and third parameters in the standard are `sender` and `receiver`. However, in the `ERC6909` contract, they are `from` and `to`. As the `Pool` contract should strictly follow the EIP6909 standard, this is a medium severity issue.
## Impact
`Pool` contract doesn't strictly follow EIP6909
## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/25a0c8aeaddec273c5318540059165696591ecfb/protocol-v2/src/lib/ERC6909.sol#L16C5-L16C114
## Tool used

Manual Review

## Recommendation
Change the 2nd and 3rd parameter names

**Comment by samuraii77** [comment]
I will escalate later based on this comment as I am eligible to do so but for some reason, it does not let me escalate.

According to this rule, the issue should be valid:
>If the protocol team provides specific information in the README or CODE COMMENTS, that information stands above all judging rules. In case of contradictions between the README and CODE COMMENTS, the README is the chosen source of truth.

>The protocol team can use the README (and only the README) to define language that indicates the codebase's restrictions and/or expected functionality. Issues that break these statements, irrespective of whether the impact is low/unknown, will be assigned Medium severity. High severity will be applied only if the issue falls into the High severity category in the judging guidelines.

The contest README specifically says that the `Pool` contract should strictly follow the `ERC6909` standard, however it does not do so.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> According to this rule, the issue should be valid:
> >If the protocol team provides specific information in the README or CODE COMMENTS, that information stands above all judging rules. In case of contradictions between the README and CODE COMMENTS, the README is the chosen source of truth.
> 
> >The protocol team can use the README (and only the README) to define language that indicates the codebase's restrictions and/or expected functionality. Issues that break these statements, irrespective of whether the impact is low/unknown, will be assigned Medium severity. High severity will be applied only if the issue falls into the High severity category in the judging guidelines.
> 
> The contest README specifically says that the `Pool` contract should strictly follow the `ERC6909` standard, however it does not do so.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by AtanasDimulski** [comment]
Escalate,
Per the above [comment](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/274#issuecomment-2352065834)

**Comment by sherlock-admin3** [comment]
> Escalate,
> Per the above [comment](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/274#issuecomment-2352065834)

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
This is not mandatory, according to the EIP documentation. To be valid issues, the ERC standard must specify that these things **MUST** be implemented. 

Planning to reject the escalation and leave the issue as is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [AtanasDimulski](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/274/#issuecomment-2352301632): rejected
