### ISSUE TITLE
000000 - A smaller amount of funds can be reallocated to a pool because of a wrong check

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-sentiment-v2-judging#275]
000000

Medium

# A smaller amount of funds can be reallocated to a pool because of a wrong check

## Summary
A smaller amount of funds can be reallocated to a pool because of a wrong check
## Vulnerability Detail
Funds can be reallocated to a different pool. First, we get the funds from one pool and then we deposit them into another one. This is the loop responsible for the second part:
```solidity
for (uint256 i; i < depositsLength; ++i) {
            uint256 poolCap = poolCapFor[deposits[i].poolId];
            // disallow deposits to pool not associated with this SuperPool
            if (poolCap == 0) revert SuperPool_PoolNotInQueue(deposits[i].poolId);
            // respect pool cap
            uint256 assetsInPool = POOL.getAssetsOf(deposits[i].poolId, address(this));
            if (assetsInPool + deposits[i].assets < poolCap) {
                ASSET.approve(address(POOL), deposits[i].assets);
                POOL.deposit(deposits[i].poolId, deposits[i].assets, address(this));
            }
        }
```
As seen, we will only deposit into a pool if the assets in the pool after the deposit will be less than the pool cap. However, the check should actually be `<=` instead of `<` as a pool should hold an amount equal to the pool cap, not less than it.
## Impact
A smaller amount of funds can be reallocated to a pool because of a wrong check
## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/25a0c8aeaddec273c5318540059165696591ecfb/protocol-v2/src/SuperPool.sol#L449
## Tool used

Manual Review

## Recommendation
Use `<=` instead of `<`

**Comment by cvetanovv** [comment]
dup of #15
