### ISSUE TITLE
000000 - Superpool contract does not strictly follow EIP4626

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-sentiment-v2-judging#279]
000000

Medium

# Superpool contract does not strictly follow EIP4626

## Summary
`Superpool` contract does not strictly follow EIP4626
## Vulnerability Detail
As mentioned in the README, the `Superpool` contract should strictly follow the EIP4626 standard. According to the EIP, these must be the parameters for the `Deposit` event:
>inputs:
    - name: sender
      indexed: true
      type: address
    - name: owner
      indexed: true
      type: address
    - name: assets
      indexed: false
      type: uint256
    - name: shares
      indexed: false
      type: uint256

However, if we take a look at the `Deposit` event in `Superpool`:
```solidity
event Deposit(address indexed caller, address indexed owner, uint256 assets, uint256 shares);
```
We can see that the first parameter is called `caller` while according to the EIP, it should be `sender`. Thus, the EIP is not strictly followed.
## Impact
`Superpool` contract does not strictly follow EIP4626
## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/25a0c8aeaddec273c5318540059165696591ecfb/protocol-v2/src/SuperPool.sol#L87
## Tool used

Manual Review

## Recommendation
Change the first parameter

**Comment by samuraii77** [comment]
According to this rule, the issue should be valid:
>If the protocol team provides specific information in the README or CODE COMMENTS, that information stands above all judging rules. In case of contradictions between the README and CODE COMMENTS, the README is the chosen source of truth.

>The protocol team can use the README (and only the README) to define language that indicates the codebase's restrictions and/or expected functionality. Issues that break these statements, irrespective of whether the impact is low/unknown, will be assigned Medium severity. High severity will be applied only if the issue falls into the High severity category in the judging guidelines.

The contest README specifically says that the `Superpool` contract should strictly follow the `ERC4626` standard, however it does not do so.

**Comment by AtanasDimulski** [comment]
Escalate,
Per the above [comment](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/279#issuecomment-2352085446)

**Comment by sherlock-admin3** [comment]
> Escalate,
> Per the above [comment](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/279#issuecomment-2352085446)
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
This is not mandatory, according to the EIP documentation. To be valid issues, the ERC standard must specify that these things **MUST** be implemented. 

Planning to reject the escalation and leave the issue as is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [AtanasDimulski](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/279/#issuecomment-2352303866): rejected
