### ISSUE TITLE
000000 - The implementation of how the discount is being applied upon the seized assets could cause liquidators to get less assets than expected

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-sentiment-v2-judging#283]
000000

Medium

# The implementation of how the discount is being applied upon the seized assets could cause liquidators to get less assets than expected

## Summary
The implementation of how the discount is being applied upon the seized assets could cause liquidators to get less assets than expected
## Vulnerability Detail
Upon liquidations, the liquidator can seize more assets than what he has paid for due to a discount being applied:
```solidity
        uint256 maxSeizedAssetValue = debtRepaidValue.mulDiv(1e18, (1e18 - discount));
        if (assetSeizedValue > maxSeizedAssetValue) {
            revert RiskModule_SeizedTooMuch(assetSeizedValue, maxSeizedAssetValue);
        }
```
The issue here is that the discount is not actually being "applied". It only checks whether the `assetSeizedValue` is at most the discounted debt. However, if the user has provided a lower value of assets to seize, he will only take that lower amount. In a way, if the user doesn't actually "ask" for the discount, he will not receive it. While every user would provide an amount of assets to seize such that they would be the maximum allowed, the issue is that a price oracle is used to calculate those values in ETH. At the time of the liquidator putting his transaction, the prices might be different than the price at the transaction execution, thus it is not possible to accurately determine how much assets he can seize and the discount might not be taken into account at all or only a fraction of the whole discount could be used up. Since the prices always move up or down, almost no user would actually be able to use up exactly `discount` amount of discount but some would be able to use just half, some 90% of the discount, some even 0 and some might even overpay.

Furthermore, there is no type of slippage to protect the user against that happening. The function can also revert in cases where the assets to seize he has provided become larger than the maximum allowed.
## Impact
The implementation of how the discount is being applied upon the seized assets could cause liquidators to get less assets than expected
## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/25a0c8aeaddec273c5318540059165696591ecfb/protocol-v2/src/RiskModule.sol#L129-L160
## Tool used

Manual Review

## Recommendation
Make it so the user always takes the maximum seized value instead of taking just the amount specified

**Comment by samuraii77** [comment]
It was never mentioned that it was intended for users to never actually get a `discount` amount of discount before or during the contest, thus we can never even know whether it is actually intended. It is much more logical for the code to apply a `discount` amount of discount while currently it does not do so and it might be completely unused, that is not how a discount works. Issue should be valid.

**Comment by AtanasDimulski** [comment]
Escalate,
Per the above [comment](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/283#issuecomment-2352089288)

**Comment by sherlock-admin3** [comment]
> Escalate,
> Per the above [comment](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/283#issuecomment-2352089288)

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
We have no problem here because the protocol wants it to work that way.

Planning to reject the escalation and leave the issue as is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [AtanasDimulski](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/283/#issuecomment-2352306783): rejected
