### ISSUE TITLE
pseudoArtist - No incentive to liquidate small position can lead to bad debts

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-sentiment-v2-judging#302]
pseudoArtist

High

# No incentive to liquidate small position can lead to bad debts

## Summary
The minBorrow can be set to 0 allowing users to borrow very small positions which will not be liquidated by the liquidators because there will be no incentive for them, and this can incur bad debt to the protocol in the long term.
## Vulnerability Detail
The

The `Sentiment` protocol doensn't enforce min Deposit and there is no logic for it , which allows user to put in small collateral. 
```solidity
 function deposit(uint256 poolId, uint256 assets, address receiver) public returns (uint256 shares) {
        PoolData storage pool = poolDataFor[poolId];

        if (pool.isPaused) revert Pool_PoolPaused(poolId);

        // update state to accrue interest since the last time accrue() was called
        accrue(pool, poolId);

        // Need to transfer before or ERC777s could reenter, or bypass the pool cap
        IERC20(pool.asset).safeTransferFrom(msg.sender, address(this), assets);

        if (pool.totalDepositAssets + assets > pool.poolCap) revert Pool_PoolCapExceeded(poolId);

        shares = _convertToShares(assets, pool.totalDepositAssets, pool.totalDepositShares, Math.Rounding.Down);
        if (shares == 0) revert Pool_ZeroSharesDeposit(poolId, assets);

        pool.totalDepositAssets += assets;
        pool.totalDepositShares += shares;

        _mint(receiver, poolId, shares);

        emit Deposit(msg.sender, receiver, assets, shares);
    }
```    

And further as mentioned in the ReadMe `Min Borrow = from 0 to 0.05 ETH = from 0 to 50000000000000000` The min Borrow amount can be set to `0` and this will allow the borrowers to borrow very small positions such that the gas cost to liquidate them is more than the incentives, which will not let liquidators choose to liquidate such positions and in the long term this will incur bad debt to the protocol.

```solidity
 if (_getValueOf(pool.asset, amt) < minBorrow) revert Pool_BorrowAmountTooLow(poolId, pool.asset, amt);
```

The above line in [Borrow function](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/Pool.sol#L429) enforces a check to refrain users from borrowing small positions but in the readme it is stated that minBorrow can be 0, and in such scenario if a user borrows very small amount the above check will easily be bypassed and so a user can easily create very small position.
With a small borrowing position (and small collateral), there is no incentive for a liquidator to liquidate the position, as the liquidation profit may not cover the liquidation cost (gas). As a result, small liquidable positions will not be liquidated, leaving bad debt to the protocol.

## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/Pool.sol#L429
## Tool used

Manual Review

## Recommendation
Do not set the `minBorrow` value to be 0.

Duplicate of #572

**Comment by PseudoArtistHacks** [comment]
@z3s can you please check why this has no medium and reward tag yet ?
This is a dupe of #572 which is a medium issue.
