### ISSUE TITLE
nfmelendez - Incorrect SuperPool Max fee check

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-sentiment-v2-judging#335]
nfmelendez

Medium

# Incorrect SuperPool Max fee check

## Summary

The protocol expects that the fee of the SuperPool is not more than 1e18 but the users can set any fee they want

## Vulnerability Detail
A user can configure a SuperPool with more fee than 100% (1e18) due to a incorrect check in the constractor that check the `fee` state variable but should check the `_fee` constructor parameter.
Then also the owner of the super pool can't fix because the `requestFeeUpdate` checks for `fee > 1e18` and  will revert  if in the constructor was set > 1e18 the fee.

## Impact
- SuperPool charging more fee than the protocol expects so functionality is broken. 

## Code Snippet

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/SuperPool.sol#L157-L158

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/SuperPool.sol#L366-L370

## Tool used

- Manual Review
- VS code

## Recommendation

Check the contructor parameter instead of the state variable in the constructor:
```javascript
        if (fee_ > 1e18) revert SuperPool_FeeTooHigh(); //@auditor changed
        fee = fee_;
```

Check the `_fee` parameter instead of `fee` in 

```javascript
    function requestFeeUpdate(uint256 _fee) external onlyOwner {
        if (_fee > 1e18) revert SuperPool_FeeTooHigh(); // @auditor changed
        pendingFeeUpdate = PendingFeeUpdate({ fee: _fee, validAfter: block.timestamp + TIMELOCK_DURATION });
        emit SuperPoolFeeUpdateRequested(_fee);
    }
```

Duplicate of #440

**Comment by nfmelendez** [comment]
Hi there, the issue says  "non-Rward" but there is another issue with same root cause that says "reward"
https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/440

**Comment by nfmelendez** [comment]
Escalate 
My issue is withoout reward but this issue with same root cause was reward: https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/440

**Comment by sherlock-admin3** [comment]
> Escalate 
> My issue is withoout reward but this issue with same root cause was reward: https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/440

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
I agree it is a duplicate of #440. Whether it will be valid will be decided by the escalation in #440.

Planning to accept the escalation and duplicate with #440.

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #440

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [nfmelendez](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/335/#issuecomment-2358805834): accepted
