### ISSUE TITLE
MohammedRizwan - Chainlink oracle will return the wrong price if the aggregator hits minAnswer

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-sentiment-v2-judging#337]
MohammedRizwan

Medium

# Chainlink oracle will return the wrong price if the aggregator hits minAnswer

## Summary
Chainlink oracle will return the wrong price if the aggregator hits minAnswer

## Vulnerability Detail
Chainlink aggregators have a built in circuit breaker if the price of an asset goes outside of a predetermined price band.
The result is that if an asset experiences a huge drop in value (i.e. LUNA crash) the price of the oracle will continue to return the minPrice instead of the actual price of the asset.
This would allow user to continue borrowing with the asset but at the wrong price. [This is exactly what happened to Venus on BSC when LUNA imploded](https://rekt.news/venus-blizz-rekt/)

In `ChainlinkEthOracle.sol`, `getValueInEth()` function has used internal function `_getPriceWithSanityChecks()` from which the price of assets in ETH from chainlink oracles are fetched and it is implemented as:

```solidity
    function getValueInEth(address asset, uint256 amt) external view returns (uint256) {
        _checkSequencerFeed();

        // [ROUND] price is rounded down. this is used for both debt and asset math, neutral effect.
        return amt.mulDiv(_getPriceWithSanityChecks(asset), (10 ** IERC20Metadata(asset).decimals()));
    }
    
    
    . . . some code . . . 
    


    function _getPriceWithSanityChecks(address asset) private view returns (uint256) {
        address feed = priceFeedFor[asset];
        (, int256 price,, uint256 updatedAt,) = IAggegregatorV3(feed).latestRoundData();
        if (price <= 0) revert ChainlinkEthOracle_NonPositivePrice(asset);
        if (updatedAt < block.timestamp - stalePriceThresholdFor[feed]) revert ChainlinkEthOracle_StalePrice(asset);
        return uint256(price);
    }
```
Here, `_getPriceWithSanityChecks()` function does not check the price acceptable range i.e `minAnswer` i.e minimum price and `maxAnswer` i.e maximum price checks.

As per the contest readme, SentimentV2 contracts would be deployed on `Any EVM-compatbile network` and it is explicitely stated that `Protocol governance will ensure that oracles are only set for standard ERC-20 tokens (plus USDC/USDT)`.

So the protocol is expected to use USDT and USDC tokens so this issue related to chainlink's `USDC/ETH` and `USDT/ETH` price feeds is applicable here.

Lets check the `minAnswer` and `maxAnswer` values of chainlink's USDC/ETH price feed on Ethereum mainnet:

`USDC/ETH price feed address`- [0x986b5E1e1755e3C2440e960477f25201B0a8bbD4](https://etherscan.io/address/0x986b5E1e1755e3C2440e960477f25201B0a8bbD4#readContract)

`USDC/ETH aggregator address`- [0x26ae9b951F84e6c28f58a92133C30e312D42e0Fe](https://etherscan.io/address/0x26ae9b951F84e6c28f58a92133C30e312D42e0Fe#readContract)

If we see the aggregator address then there is `minAnswer` and `maxAnswer` price values present which are stated as below:

`minAnswer`- 1 
`maxAnswer`- 95780971304118053647396689196894323976171195136475135

This means if USDC/ETH falls below the `minAnswer` or rises above `maxAnswer`, the price feed would take 1 or 9578......135 as the answer, which is unexpected.

It should be noted that, `getValueInEth()` function is used to fetch asset value in ETH in following contracts functions.

1) In `Pool.sol` having internal function `_getValueOf()` which is further used in functions like `borrow()` function to borrow shares and `repay()` function to repay the debt

2) In `RiskModule.sol` having internal function `_validateSeizedAssetValue()` which is further used in functions like `validateLiquidation()` to validate liquidator data and value of assets seized. 

Thereofore, both of these contracts functionalities are largely affected.

## Impact
Due to no handling logic if the prices reaches below minAnswer or above maxAnswer for chainlink oracles then it would cause the incorrect return of asset prices as mentioned in above contracts functionalities.

## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/oracle/ChainlinkEthOracle.sol#L101

## Tool used
Manual Review

## Recommendation
Consider using the following checks.

For example:

```solidity
(uint80, int256 answer, uint, uint, uint80) = oracle.latestRoundData();

// minPrice check
require(answer > minPrice, "Min price exceeded");
// maxPrice check
require(answer < maxPrice, "Max price exceeded");
```

Duplicate of #570

**Comment by 0xIronMan** [comment]
Escalate

This is wrongly excluded and should be considered valid as per sherlock rule. 

> Chainlink Price Checks: Issues related to minAnswer and maxAnswer checks on Chainlink's Price Feeds are considered medium only if the Watson explicitly mentions the price feeds (e.g. USDC/ETH) that require this check.

The issue particulaly mentions USDC/USDT ETH pairs.

>  the protocol is expected to use USDT and USDC tokens so this issue related to chainlink's USDC/ETH and USDT/ETH price feeds is applicable here.

Therefore, i believe its a valid medium issue.
