### ISSUE TITLE
Yashar - A previously known spender can drain assets due to inability to revoke allowance

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-sentiment-v2-judging#417]
Yashar

Medium

# A previously known spender can drain assets due to inability to revoke allowance

## Summary
If a spender is removed from the `isKnownSpender` mapping, users cannot decrease their allowance, potentially allowing a malicious spender to continue transferring assets.

## Vulnerability Detail
The owner or authorized operator of a position [can approve](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/PositionManager.sol#L341-L358) an amount of assets to a spender using `approve` function. For this to occur, the spender must be listed in the `isKnownSpender` mapping:
```solidity
        if (!isKnownSpender[spender]) revert PositionManager_UnknownSpender(spender);
```

If the protocol removes a spender from the `isKnownSpender` mapping due to reasons such as malicious actions or getting compromised, the owner of a position will be unable to decrease the allowance of the malicious spender because the transaction will revert [at this line](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/PositionManager.sol#L351):
```solidity
        if (!isKnownSpender[spender]) revert PositionManager_UnknownSpender(spender);
```
As a result, the malicious spender can still transfer the assets to themselves.

## Impact
Users may lose funds because they are unable to clear the allowance of a previously known spender.

## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/PositionManager.sol#L341-L358

## Tool used

Manual Review

## Recommendation
Allow users to decrease the allowance to zero even if the spender is no longer known:

```diff
    /// @dev Approve a spender to use assets from a position
    function approve(address position, bytes calldata data) internal {
        // data -> abi.encodePacked(address, address, uint256)
        // spender -> [0:20] address to be approved
        // asset -> [20:40] address of token to be approves
        // amt -> [40:72] amount of asset to be approved
        address spender = address(bytes20(data[0:20]));
        address asset = address(bytes20(data[20:40]));
        uint256 amt = uint256(bytes32(data[40:72]));

        if (!isKnownAsset[asset]) revert PositionManager_ApproveUnknownAsset(asset);
-       if (!isKnownSpender[spender]) revert PositionManager_UnknownSpender(spender);
+       if (amt > 0 && !isKnownSpender[spender]) {
+            revert PositionManager_UnknownSpender(spender);
+       }

        // if the passed amt is type(uint).max assume approval of the entire balance
        if (amt == type(uint256).max) amt = IERC20(asset).balanceOf(position);

        Position(payable(position)).approve(asset, spender, amt);
        emit Approve(position, msg.sender, spender, asset, amt);
    }
```

Duplicate of #442

**Comment by yashar0x** [comment]
escalate

kindly check [this comment](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/442#issuecomment-2355030758) under the primary report

**Comment by sherlock-admin3** [comment]
> escalate
> 
> kindly check [this comment](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/442#issuecomment-2355030758) under the primary report

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
@yashar0x No need to escalate this issue, too. The main one is enough.

I'll reject the escalation, and this issue will remain duplicated with the other issue. The other escalation will decide the severity and whether it will be valid/invalid.

**Comment by Evert0x** [comment]
Result:
Invalid
Duplicate of #442

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [yashar0x](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/417/#issuecomment-2355045372): rejected

**Comment by yashar0x** [comment]
hey @cvetanovv 
didn't know that, sorry!
