### ISSUE TITLE
tvdung94 - Users wont be able to set approve 0 for unknown spenders in an edge case

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-sentiment-v2-judging#442]
tvdung94

Medium

# Users wont be able to set approve 0 for unknown spenders in an edge case

## Summary
Users wont be able to set approve 0 for unknown spenders, which was previous known and was approved max.
## Vulnerability Detail
PositionManager::approve() will revert if a spender is unknown
```solidity
if (!isKnownSpender[spender]) revert PositionManager_UnknownSpender(spender);
```
The problem is that it does not consider the case where the unknown spender was previously known and has been approved max by the user. In this case, there is no way to approve 0 this unknown spender, and it can still freely move the asset token in position toother places, since after being approved max,  allowance wont be decreased after transfer for most erc20 tokens.

Consider this scenario:
1. Spender A has been added into known spender.
2. User B has approved max spender A for their position.
3. Spender A is now removed from known spender (becoming unknown spender).
4. Spender A still have max allowance of user B' position and can transfer user B' allowed token anytime.
5. There is no way for user B to approve 0 this spender A.
## Impact
Unknown spenders in this scenario can freely transfer money from positions to other places. Might be risky if the spender is malicious.
## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/PositionManager.sol#L351
## Tool used

Manual Review

## Recommendation
Consider checking position's allowance for this spender; if it is not 0, it means that this spender was known before so allowance should be set to 0; 

```solidity
if (!isKnownSpender[spender]) { 
      if (asset.allowance(position, spender) != 0) {
            Position(payable(position)).approve(asset, spender, 0);
      } else {
         revert PositionManager_UnknownSpender(spender);
      }
};
```

**Comment by yashar0x** [comment]
escalate

I don’t think spinning up a new position is a good solution here. The user might have borrowed tokens using the current position and could be locked into other protocols, making it hard to repay the loan and close the position right away. In this case, they'd still be exposed to risk because the old spender can keep transferring tokens due to the max approval. So, the user can't just start fresh without first fixing this issue.
it's a valid medium

**Comment by sherlock-admin3** [comment]
> escalate
> 
> I don’t think spinning up a new position is a good solution here. The user might have borrowed tokens using the current position and could be locked into other protocols, making it hard to repay the loan and close the position right away. In this case, they'd still be exposed to risk because the old spender can keep transferring tokens due to the max approval. So, the user can't just start fresh without first fixing this issue.
> it's a valid medium

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
You are right that the normal user may become malicious and have to reduce his allowance. However, the problem comes after the admin removes the user from `isKnownSpender[spender]`. 

This means that we have to respect the admin assumptions rule:

> An admin action can break certain assumptions about the functioning of the code.

Planning to reject the escalation and leave the issue as is.

**Comment by Evert0x** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [yashar0x](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/442/#issuecomment-2355030758): rejected
