### ISSUE TITLE
eLSeR17 - Pool::initializePool() could prevent another user from creating the Pool with the dedired parameters

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-sentiment-v2-judging#445]
eLSeR17

Medium

# Pool::initializePool() could prevent another user from creating the Pool with the dedired parameters

## Summary
Pool::initializePool() could prevent another user from creating the Pool with the dedired parameters

## Vulnerability Detail
When initializing a new pool in Pool contract, poolId determined like this:
```solidity
poolId = uint256(keccak256(abi.encodePacked(owner, asset, rateModelKey)));
```
Which means that only one pool can exist for the same owner, asset and rateModelKey. This pool can be created by anybody on behalf of another owner, and the current data of modelRate, defaultInterestFee and defaultOriginationFee will be taken. Owner on behalf pool has been initialized may not like the values of these parameters at the moment when the function was called and they cannot change these parameters nor create another pool with different ones. Take into account that parameters like defaultInterestFee or defaultOriginationFee can only be modified by Pool contract's owner; and not by poolId's owner.

## Impact
A owner can be prevented from initializing their poolId with the parameters they desire, as this pool allows anybody to initialize a pool on behalf another owner for a unique time.

## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/Pool.sol#L562-L598

## Tool used
Manual Review

## Recommendation
Allow only msg.sender to initialize a pool for themselves, as there are no benefits in iniaitlizing a pool on behalf of another owner.

```solidity
 function initializePool(
-       address owner,
        address asset,
        uint128 poolCap,
        bytes32 rateModelKey
    ) external returns (uint256 poolId) {
-       if (owner == address(0)) revert Pool_ZeroAddressOwner();

        if (RiskEngine(riskEngine).getOracleFor(asset) == address(0)) revert Pool_OracleNotFound(asset);

        address rateModel = Registry(registry).rateModelFor(rateModelKey);
        if (rateModel == address(0)) revert Pool_RateModelNotFound(rateModelKey);

-       poolId = uint256(keccak256(abi.encodePacked(owner, asset, rateModelKey)));
+      poolId = uint256(keccak256(abi.encodePacked(msg.sender, asset, rateModelKey)));
        if (ownerOf[poolId] != address(0)) revert Pool_PoolAlreadyInitialized(poolId);
-        ownerOf[poolId] = owner;
+       ownerOf[poolId] = msg.sender;
        PoolData memory poolData = PoolData({
            isPaused: false,
            asset: asset,
            rateModel: rateModel,
            poolCap: poolCap,
            lastUpdated: uint128(block.timestamp),
            interestFee: defaultInterestFee,
            originationFee: defaultOriginationFee,
            totalBorrowAssets: 0,
            totalBorrowShares: 0,
            totalDepositAssets: 0,
            totalDepositShares: 0
        });

        poolDataFor[poolId] = poolData;

-       emit PoolInitialized(poolId, owner, asset);
+      emit PoolInitialized(poolId, msg.sender, asset);
        emit RateModelUpdated(poolId, rateModel);
        emit PoolCapSet(poolId, poolCap);
    }
```

Duplicate of #588

**Comment by ruvaag** [comment]
there is nothing other than `poolCap` that can be frontrun, which can be easily modified by the owner. Should be a low or invalid
