### ISSUE TITLE
Obsidian - The SuperPool withdrawal queue can be bypassed

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-sentiment-v2-judging#462]
Obsidian

Medium

# The SuperPool withdrawal queue can be bypassed

## Summary
See detail

## Vulnerability Detail
The SuperPool attempts to withdraw from base pools, sequentially according to the `withdrawQueue` order set by the creator.

However, it can only withdraw the available assets from each base pool.

Assume a SuperPool which provides liquidity to 3 base pools: $A, B, C$-  with the withdrawal queue in that order
Anyone with funds deposited in the SuperPool can bypass the intended withdrawal queue order in the following steps:

1. Get a large flash loan (with 0 fees)
2. Deposit the loaned tokens as collateral 
3. Borrow the maximum amount from pools $A$ and $B$
4. Withdraw from the SuperPool, funds will be withdrawn from $C$ since $A$ and $B$ have max utilisation
5. Repay the borrowed tokens from $A$ and $B$
6. Withdraw the collateral (0 interest since it is in the same transaction)
7. Repay the flash loan

## Impact
Intended withdrawal queue order is bypassed

## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/SuperPool.sol#L565

## Tool used
Manual Review

**Comment by 0xjuaan** [comment]
Escalate

The Lead Judge comment "Admins are trusted" is not relevant to this issue, since this does not require any admin action

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> The Lead Judge comment "Admins are trusted" is not relevant to this issue, since this does not require any admin action

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
Agreed with the comment that "Admin is trusted" is no reason for this issue to be invalid. 

However, this issue is not enough for Medium severity. That `withdrawQueue` can be bypassed is Low severity. 

The issue doesn't explain what the impact would be on the protocol if this is bypassed. 

Just because `withdrawQueue` can be bypassed does not mean that "core contract functionality" is broken. On the contrary, `withdrawQueue` functionality works.

Planning to reject the escalation and leave the issue as is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xjuaan](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/462/#issuecomment-2353384486): rejected
