### ISSUE TITLE
xtesias - _maxWithdraw will return a completely wrong value when totalBalance < assetsInPool

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-sentiment-v2-judging#468]
xtesias

Medium

# _maxWithdraw will return a completely wrong value when totalBalance < assetsInPool

### Summary

When checking the max withdraw amount the function _maxWithdraw makes a call to `POOL::getLiquidityOf` to know how much liquid asset the pool has to add to the balance of the super pool itself, to know how much the users can withdraw, but when balance of the asset in the pool contract is less than the liquid Asset in the pool, for all pools or even in one it returns a completely inflated value due to the loop

### Root Cause

In the [SuperPool._maxWithdraw::L474](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/SuperPool.sol#L474C5-L485C6) when it tries to calculate the max amount user can withdraw based on the liquidity in the super pool and the pool, it loops through the depositQueue to check liquidity for that asset in each pool as shown below 
```solidity
 uint256 totalLiquidity; // max assets that can be withdrawn based on superpool and underlying pool liquidity
        uint256 depositQueueLength = depositQueue.length;
        for (uint256 i; i < depositQueueLength; ++i) {
            totalLiquidity += POOL.getLiquidityOf(depositQueue[i]);
        }
        totalLiquidity += ASSET.balanceOf(address(this));
```
As you see it tries to loop through the pools to get the liquid asset amount, the main issue is how this function interacts with [POOL.getLiquidityOf](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/Pool.sol#L210C5-L215C6) as shown below 

```solidity
function getLiquidityOf(uint256 poolId) public view returns (uint256) {
        PoolData storage pool = poolDataFor[poolId];
        uint256 assetsInPool = pool.totalDepositAssets - pool.totalBorrowAssets;
        uint256 totalBalance = IERC20(pool.asset).balanceOf(address(this));
        return (totalBalance > assetsInPool) ? assetsInPool : totalBalance;
    }
```
Now to explain what can go wrong with this implementation, if in the first pool looped through the totalBalance is < assetInPool, the totalBalance is returned, now the next pool to be looped through, also would have a high probability that totalBalance < assetInPool, which will also return totalBalance and add it to the balance if the first pool, same thing would happen to the  third pool
To VISUALIZE 
totalBalance of the asset = 100 tokens, for the three pools the `totalLiquidity` will be equals to 300, which is completely wrong as loop is reusing the same amount of asset thinking its a different asset amount, meanwhile, it is just referencing the same 100 token balance of the asset in the `POOL`
To expand this issue will occur either ways even though one of the 3 pools uses the totalbalance of the pool, as the other pools where `totalBalance > assetsInPool` is true and they use the assetInPools.

### Internal pre-conditions

- Users must have deposited to the pools 
- The pools must have borrowed from which would reduce the liquid assets in the pool
- The total balance of the pools must be less the assetInPool for at least one pool

### Impact

The maxWithdraw is a variable is a critical function that determines the max amount a user can withdraw from the pool, based on the liquid asset available, if those liquid asset balances are inflated, it will certainly cause DOS of the withdrawal functionality as the `POOL` will not have enough assets to fulfill the withdrawals

Duplicate of #110

**Comment by ruvaag** [comment]
I don't think this is a duplicate of #110 which is about ERC4626 compliance

besides, this should actually be invalid because `return (totalBalance > assetsInPool) ? assetsInPool : totalBalance;` is a redundant check. i cannot think of a scenario where the totalBalance of the POOL would be less than the sum of the liqudity of the internal pools
