### ISSUE TITLE
LonWof-Demon - Lack of `SuperPool` Cap Check in Accrual and Deposit Functions

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-sentiment-v2-judging#496]
LonWof-Demon

Medium

# Lack of `SuperPool` Cap Check in Accrual and Deposit Functions

## Summary
The current implementation of the `accrue` and `_deposit` functions in the `SuperPool` contract has a potential issue where the `lastTotalAssets` can exceed the `superPoolCap`. This issue arises because `lastTotalAssets` is updated based on deposits without a check to ensure it does not surpass the `superPoolCap`. Additionally, the interest accrued is added to `lastTotalAssets`, potentially causing it to exceed the cap and affect new deposits.

## Vulnerability Detail

1. **Lack of Cap Check During Accrual:**
   - **Issue:** The `accrue` function updates `lastTotalAssets` based on the simulated accrual of fees and interest, but it does not include a check to ensure that `lastTotalAssets` does not exceed `superPoolCap`.
   - **Potential Impact:** If the accrued interest and deposited assets cause `lastTotalAssets` to exceed `superPoolCap`, this could lead to incorrect state management and the inability to process further deposits correctly.

2. **Inconsistent Cap Enforcement:**
   - **Issue:** The `_deposit` function checks whether the total assets (`lastTotalAssets` + new deposit) exceed the `superPoolCap` before allowing the deposit. However, this check occurs after `lastTotalAssets` has already been updated with accrued interest.
   - **Potential Impact:** If `lastTotalAssets` has already been inflated by accrued interest, the `superPoolCap` check may not prevent the cap from being exceeded if the combined value of interest and new deposits is too high.
## Impact

- **SuperPool Cap Breach:** There is a risk that `lastTotalAssets` may exceed the `superPoolCap`, which could disrupt deposit processing and lead to potential security issues or operational problems.
- **Incorrect Asset Management:** If `lastTotalAssets` surpasses the cap, the integrity of asset management and cap enforcement within the `SuperPool` is compromised, potentially allowing more deposits than intended.

## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/SuperPool.sol#L499
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/SuperPool.sol#L314
```solidity
function accrue() public {
    (uint256 feeShares, uint256 newTotalAssets) = simulateAccrue();
    if (feeShares != 0) ERC20._mint(feeRecipient, feeShares);
    lastTotalAssets = newTotalAssets;
}

function simulateAccrue() internal view returns (uint256, uint256) {
    uint256 newTotalAssets = totalAssets();
    uint256 interestAccrued = (newTotalAssets > lastTotalAssets) ? newTotalAssets - lastTotalAssets : 0;
    if (interestAccrued == 0 || fee == 0) return (0, newTotalAssets);

    uint256 feeAssets = interestAccrued.mulDiv(fee, WAD);
    uint256 feeShares = _convertToShares(feeAssets, newTotalAssets - feeAssets, totalSupply(), Math.Rounding.Down);

    return (feeShares, newTotalAssets);
}

function _deposit(address receiver, uint256 assets, uint256 shares) internal {
    if (lastTotalAssets + assets > superPoolCap) revert SuperPool_SuperPoolCapReached();
    ASSET.safeTransferFrom(msg.sender, address(this), assets);
    ERC20._mint(receiver, shares);
    _supplyToPools(assets);
    lastTotalAssets += assets; // lastTotalAsset is total asset in super pool
    emit Deposit(msg.sender, receiver, assets, shares);
}
```
## Tool used

Manual Review

## Recommendation
Implement Cap Check During Accrual:- Add a check in the `accrue` function to ensure that `lastTotalAssets` does not exceed `superPoolCap` after updating with accrued interest.

Duplicate of #532

**Comment by LonWof-Demon** [comment]
Escalate
@z3s could you provide the reason for invalidating the bug

**Comment by sherlock-admin3** [comment]
> Escalate
> @z3s could you provide the reason for invalidating the bug 

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by recursiveEth** [comment]
@z3s could you provide the reason for invalidating the bug,  they need to check before accruing the asset in the vault. it's a valid bug

**Comment by sherlock-admin3** [comment]
> Escalate 
> @z3s could you provide the reason for invalidating the bug,  they need to check before accruing the asset in the vault. it's a valid bug
> 

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).
