### ISSUE TITLE
dhank - User can revert the `positionBeacon`  value set by  the ADMIN.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-sentiment-v2-judging#506]
dhank

Medium

# User can revert the `positionBeacon`  value set by  the ADMIN.

## Summary
User can revert the `positionBeacon`  value set by  the ADMIN.

## Vulnerability Detail
Using  the `setBeacon()` , owner can change the value of `positionBeacon` to a  new Address.

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/PositionManager.sol#L503-L506

At the same time we have `updateRegistry()` which is a public function where the positionBeacon is set from the values of Registr contract.
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/PositionManager.sol#L204-L208

    function updateFromRegistry() public {
        pool = Pool(registry.addressFor(SENTIMENT_POOL_KEY));
        riskEngine = RiskEngine(registry.addressFor(SENTIMENT_RISK_ENGINE_KEY));
        positionBeacon = registry.addressFor(SENTIMENT_POSITION_BEACON_KEY);
    }
## Impact
Any User can revert the `positionBeacon`  value set by  the ADMIN.

## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/PositionManager.sol#L204-L208

## Tool used

Manual Review

## Recommendation

positionBeacon update can be omiited from the updateRegistry.

**Comment by iamnmt** [comment]
Escalate

Invalid.

The function `PositionManager#setBeacon` is redundant. 

The admin sets the beacon for `PositionManager` by calling `Registry#setAddress => PositionManager#updateFromRegistry`.

The value from `Registry` is the source of truth, and `PositionManager` should update its beacon according to that.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Invalid.
> 
> The function `PositionManager#setBeacon` is redundant. 
> 
> The admin sets the beacon for `PositionManager` by calling `Registry#setAddress => PositionManager#updateFromRegistry`.
> 
> The value from `Registry` is the source of truth, and `PositionManager` should update its beacon according to that.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by samuraii77** [comment]
It's also an admin error, they can avoid that from happening by simply updating the registry.

**Comment by cvetanovv** [comment]
I agree with @iamnmt and @samuraii77 comments. 

Admin can prevent this. If he doesn't, it's his mistake.

Planning to accept the escalation and invalidate the issue.

**Comment by Evert0x** [comment]
Result:
Invalid
Has Duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [iamnmt](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/506/#issuecomment-2351835982): accepted
