### ISSUE TITLE
KupiaSec - Incorrect Fee Update Invalidation

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-sentiment-v2-judging#528]
KupiaSec

Medium

# Incorrect Fee Update Invalidation

## Summary
In the `SuperPool` contract, a validation error occurs when updating the `fee` state variable. The validation process incorrectly checks the existing state variable instead of the incoming parameter.

## Vulnerability Detail
The same thing happens in both `constructor` and `requestFeeUpdate` function.

In the constructor, the validation mistakenly checks `fee` instead of the incoming `fee_` parameter, which always passes since the default value is 0.

```solidity
    constructor(
        address pool_,
        address asset_,
        address feeRecipient_,
        uint256 fee_,
        uint256 superPoolCap_,
        string memory name_,
        string memory symbol_
    ) Ownable() ERC20(name_, symbol_) {
        POOL = Pool(pool_);
        ASSET = IERC20(asset_);
        DECIMALS = _tryGetAssetDecimals(ASSET);

>       if (fee > 1e18) revert SuperPool_FeeTooHigh();
        fee = fee_;
        feeRecipient = feeRecipient_;
        superPoolCap = superPoolCap_;
    }
```

In the `requestFeeUpdate` function, the validation mistakenly checks `fee` instead of the incoming `_fee` parameter, which always passes since the default value is 0.

```solidity
    function requestFeeUpdate(uint256 _fee) external onlyOwner {
>       if (fee > 1e18) revert SuperPool_FeeTooHigh();
        pendingFeeUpdate = PendingFeeUpdate({ fee: _fee, validAfter: block.timestamp + TIMELOCK_DURATION });
        emit SuperPoolFeeUpdateRequested(_fee);
    }
```

## Impact
Because of incorrect validation, an excessively high fee value can be set, leading to an unexpected amount of funds being deducted as a fee.

## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/SuperPool.sol#L157

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/SuperPool.sol#L367

## Tool used
Manual Review

## Recommendation
Modify the validation to:
```diff
    constructor(
        address pool_,
        address asset_,
        address feeRecipient_,
        uint256 fee_,
        uint256 superPoolCap_,
        string memory name_,
        string memory symbol_
    ) Ownable() ERC20(name_, symbol_) {
        POOL = Pool(pool_);
        ASSET = IERC20(asset_);
        DECIMALS = _tryGetAssetDecimals(ASSET);

-       if (fee > 1e18) revert SuperPool_FeeTooHigh();
+       if (fee_ > 1e18) revert SuperPool_FeeTooHigh();
        fee = fee_;
        feeRecipient = feeRecipient_;
        superPoolCap = superPoolCap_;
    }
```
and
```diff
    function requestFeeUpdate(uint256 _fee) external onlyOwner {
-       if (fee > 1e18) revert SuperPool_FeeTooHigh();
+       if (_fee > 1e18) revert SuperPool_FeeTooHigh();
        pendingFeeUpdate = PendingFeeUpdate({ fee: _fee, validAfter: block.timestamp + TIMELOCK_DURATION });
        emit SuperPoolFeeUpdateRequested(_fee);
    }
```

**Comment by KupiaSecAdmin** [comment]
Escalate

Hi @z3s
I'd like to highlight a few important points:

1. Setting these fees to incorrect values, particularly excessively high ones, can significantly disrupt user experience, leading to substantial negative impacts.
2. It violates the invariant to maintain fees within a specified range, a condition that should never occur.
3. Every component in the code must function correctly and with clear intent; otherwise, it compromises the system's integrity and might be better removed.
4. Even if trusted parties are unlikely to act maliciously or be manipulated, with the catastrophic potential of such an event I believe this as a valid concern.

Thank you for taking the time to reconsider this issue!

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Hi @z3s
> I'd like to highlight a few important points:
> 
> 1. Setting these fees to incorrect values, particularly excessively high ones, can significantly disrupt user experience, leading to substantial negative impacts.
> 2. It violates the invariant to maintain fees within a specified range, a condition that should never occur.
> 3. Every component in the code must function correctly and with clear intent; otherwise, it compromises the system's integrity and might be better removed.
> 4. Even if trusted parties are unlikely to act maliciously or be manipulated, with the catastrophic potential of such an event I believe this as a valid concern.
> 
> Thank you for taking the time to reconsider this issue!

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ruvaag** [comment]
duplicate of #440 ?

**Comment by cvetanovv** [comment]
I agree that this issue is a duplicate of #440, but I will reject the escalation because it is invalid. You can see the comment I left on the main issue: https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/440#issuecomment-2373996667

Planning to reject the escalation and leave the issue as is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [KupiaSecAdmin](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/528/#issuecomment-2352231067): rejected
