### ISSUE TITLE
KupiaSec - Reward tokens from external protocols, such as GMX, are not accurately accounted for

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-sentiment-v2-judging#531]
KupiaSec

High

# Reward tokens from external protocols, such as GMX, are not accurately accounted for

## Summary

If the position owner stakes position assets in the GMX protocol, rewards will accrue for that position. However, when assessing the health of the position, unclaimed rewards are not considered part of the position's assets. This oversight could lead to illegitimate liquidations. Additionally, if the reward tokens are not classified as `knownAsset`, the position owner cannot transfer these tokens, as transferring position assets requires them to be `knownAsset`.

## Vulnerability Detail

Position owners can stake their assets in the GMX protocol. When assets are staked, corresponding rewards accrue for the position, and the owners can claim these rewards (see [allowed function list](https://gist.github.com/ruvaag/58c9fc2e5c139451c83c21fda27b77a2)). However, the protocol does not accurately account for the rewards from GMX as part of the position assets.

1. If the reward tokens are not classified as `knownAsset`, the position owner can't transfer the rewards that arrived at the position, as transferring requires tokens to be `knownAsset`. As a result, the rewards remain inaccessible.
    ```solidity
        function transfer(address position, bytes calldata data) internal {
            // data -> abi.encodePacked(address, address, uint256)
            // recipient -> [0:20] address that will receive the transferred tokens
            // asset -> [20:40] address of token to be transferred
            // amt -> [40:72] amount of asset to be transferred
            address recipient = address(bytes20(data[0:20]));
            address asset = address(bytes20(data[20:40]));
            uint256 amt = uint256(bytes32(data[40:72]));

    316     if (!isKnownAsset[asset]) revert PositionManager_TransferUnknownAsset(asset);

            // if the passed amt is type(uint).max assume transfer of the entire balance
            if (amt == type(uint256).max) amt = IERC20(asset).balanceOf(position);

            Position(payable(position)).transfer(recipient, asset, amt);
            emit Transfer(position, msg.sender, recipient, asset, amt);
        }
    ```

2. Even if the reward tokens are classified as `knownAsset`, the health check does not include unclaimed rewards as part of the position's assets.

    In the [RiskModule.isPositionHealthy()](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/RiskModule.sol#L67-L85) function, unclaimed rewards are not factored into the position's health assessment. This oversight could lead to unfair liquidations, even when the position owner could avoid liquidation by claiming rewards to increase the position's asset value. Furthermore, after liquidation, all position assets, including the staked tokens in the GMX protocol, are sent to the liquidator, allowing them to claim rewards that should rightfully belong to the position owner.

## Impact

1. If the reward tokens from the GMX protocol are not classified as `knownAsset`, the position owner cannot transfer them.
2. Even if the reward tokens are classified as `knownAsset`, positions may be unfairly liquidated because unclaimed rewards are not included in the position's asset calculations.

## Code Snippet

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/PositionManager.sol#L307-L323

## Tool used

Manual Review

## Recommendation

The protocol should include the rewards from the GMX protocol as part of the position's assets.

**Comment by KupiaSecAdmin** [comment]
Escalate

I believe this issue is a valid one.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> I believe this issue is a valid one.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ruvaag** [comment]
I can confirm this is intended.

In the case of reward tokens we will recognize them as a knownAsset to allow claims and transfers. reward tokens are often illiquid and volatilie, and we'll avoid registering an oracle for such assets.

**Comment by cvetanovv** [comment]
The sponsor with the last comment confirms that this intended and we have no issue.

Planning to reject the escalation and leave the issue as is.

**Comment by KupiaSecAdmin** [comment]
> In the case of reward tokens we will recognize them as a knownAsset to allow claims and transfers. reward tokens are often illiquid and volatilie, and we'll avoid registering an oracle for such assets.

If the reward tokens are `knownAsset`s and do not have oracles, the `RiskModule.isPositionHealthy()` function will revert for that position. This occurs because it calls the `_getPositionAssetData()` function, which calculates asset values for all the `knownAsset`s in the position. The calculation of asset values for the reward tokens will revert since these tokens lack oracles.

```
    function isPositionHealthy(address position) public view returns (bool) {
        ...

        (uint256 totalAssetValue, address[] memory positionAssets, uint256[] memory positionAssetWeight) =
79          _getPositionAssetData(position);
        ...

---------------------------

    function _getPositionAssetData(address position)
        ...

        for (uint256 i; i < positionAssetsLength; ++i) {
233         uint256 assets = getAssetValue(position, positionAssets[i]);
            // positionAssetData[i] stores value of positionAssets[i] in eth
            positionAssetData[i] = assets;
            totalAssetValue += assets;
        }

        ...

---------------------------

    function getAssetValue(address position, address asset) public view returns (uint256) {
184     IOracle oracle = IOracle(riskEngine.getOracleFor(asset));
        uint256 amt = IERC20(asset).balanceOf(position);
        return oracle.getValueInEth(asset, amt);
    }
```

So, if the reward tokens are `knownAsset`s, they should have oracles. Therefore, unclaimed rewards should be included in the health check.

**Comment by cvetanovv** [comment]
We can see that this is a intentional design of the protocol. The sponsor has clearly explained that reward tokens like those from GMX are often illiquid and volatile, and including them in the health checks could introduce unnecessary complexity and instability. 

This issue falls entirely into the "design decision" category.

My decision to reject the escalation remains.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [KupiaSecAdmin](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/531/#issuecomment-2358614489): rejected
