### ISSUE TITLE
admin - Lack of Feed Address Zero Check at _getPriceWithSanityChecks function for ChainlinkEthOracle contract

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-sentiment-v2-judging#56]
admin

Medium

# Lack of Feed Address Zero Check at _getPriceWithSanityChecks function for ChainlinkEthOracle contract

### Summary

Link: https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/oracle/ChainlinkEthOracle.sol#L99

The contract does not check if the feed address is address(0) before interacting with it. If an invalid address is used, it could lead to unintended behavior or errors.

### Root Cause

Lack of address validation

### Impact

If an invalid address is used, it could lead to unintended behavior or errors.

### Mitigation

Add checks to ensure that the feed address is not address(0) before using it in functions like _getPriceWithSanityChecks.

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sentimentxyz/protocol-v2/pull/321
