### ISSUE TITLE
hash - `feeRecipeint` lacks setter function

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-sentiment-v2-judging#571]
hash

Medium

# `feeRecipeint` lacks setter function

## Summary
`feeRecipeint` lacks setter function

## Vulnerability Detail
The `feeRecipient` variable of Pool.sol is intended to be updated but lacks a setter function and hence cannot be updated

## Impact
`feeRecipient` cannot be updated

## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/Pool.sol#L50

## Tool used
Manual Review

## Recommendation
Add a setter function

**Comment by AuditorPraise** [comment]
feeRecipient is set in the initialize function or no?

**Comment by cawfree** [comment]
Escalate

This finding is ineligible for Sherlock's issue severity criteria for a medium issue:

> 1. **Causes a loss of funds** but requires certain external conditions or specific states, or a loss is highly constrained. The loss of the affected party must exceed 0.01% and 10 USD.
>
> 2. **Breaks core contract functionality**, rendering the contract useless or leading to loss of funds of the affected party larger than 0.01% and 10 USD.

Lacking the ability to update a `feeRecipient`, whilst nice to have, is not satisfactory for issue criteria as this finding presents no risk.

There is no loss of funds and no core contract functionality is broken; rather, this is a suggestion for improvement by recommending a new feature.

Furthermore, [this contract is upgradeable](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/Pool.sol#L25C18-L25C36), so this functionality could be introduced at a later point in time.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This finding is ineligible for Sherlock's issue severity criteria for a medium issue:
> 
> > 1. **Causes a loss of funds** but requires certain external conditions or specific states, or a loss is highly constrained. The loss of the affected party must exceed 0.01% and 10 USD.
> >
> > 2. **Breaks core contract functionality**, rendering the contract useless or leading to loss of funds of the affected party larger than 0.01% and 10 USD.
> 
> Lacking the ability to update a `feeRecipient`, whilst nice to have, is not satisfactory for issue criteria as this finding presents no risk.
> 
> There is no loss of funds and no core contract functionality is broken; rather, this is a suggestion for improvement by recommending a new feature.
> 
> Furthermore, [this contract is upgradeable](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/Pool.sol#L25C18-L25C36), so this functionality could be introduced at a later point in time.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by iamnmt** [comment]
@cawfree 

The rules that you quoted are not applied in this contest.

This issue should be low because:
- `feeRecipeint` can be set in the initialization
- Updating `feeRecipeint` is not a core contract functionality for this issue to be qualified for medium

**Comment by cvetanovv** [comment]
I agree with both comments. The severity is not enough for Medium. 

`feeRecipeint` will be set in the initialization, and the fact that it cannot be updated does not mean that the core functionality of the contract is broken. That's why I think this issue is Low severity.

Planning to accept the escalation and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [cawfree](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/571/#issuecomment-2351828219): accepted

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sentimentxyz/protocol-v2/pull/322
