### ISSUE TITLE
cawfree - `riskModule` Can Be Permissionlessly Reset

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-sentiment-v2-judging#82]
cawfree

Medium

# `riskModule` Can Be Permissionlessly Reset

## Summary

The [`RiskEngine`](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/RiskEngine.sol) provides the owner with the elevated capability to override the [`riskModule`](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/25a0c8aeaddec273c5318540059165696591ecfb/protocol-v2/src/RiskEngine.sol#L54C23-L54C33), however this setting can be permissionlessly undone by users.

## Vulnerability Detail

The [`RiskEngine`](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/RiskEngine.sol) provides the owner with the elevated permission to modify [`riskModule`](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/25a0c8aeaddec273c5318540059165696591ecfb/protocol-v2/src/RiskEngine.sol#L54C23-L54C33) via a call to [`setRiskModule`](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/25a0c8aeaddec273c5318540059165696591ecfb/protocol-v2/src/RiskEngine.sol#L235C14-L235C27):

```solidity
/// @notice Set the risk module used to store risk logic for positions
/// @dev only callable by RiskEngine owner
/// @param _riskModule the address of the risk module implementation
function setRiskModule(address _riskModule) external onlyOwner {
    riskModule = RiskModule(_riskModule);

    emit RiskModuleSet(_riskModule);
}
```

However, the [`RiskEngine`](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/RiskEngine.sol) also defines the capability for any protocol user to permissionlessly inherit the [`RiskEngine`](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/RiskEngine.sol) setting from the registry:

```solidity
/// @notice Fetch and update module addreses from the registry
function updateFromRegistry() external { /// @audit permissionless
    pool = Pool(REGISTRY.addressFor(SENTIMENT_POOL_KEY));
    riskModule = RiskModule(REGISTRY.addressFor(SENTIMENT_RISK_MODULE_KEY)); /// @audit writes_riskModule

    emit PoolSet(address(pool));
    emit RiskModuleSet(address(riskModule));
}
```

Due to this permissionless implementation, it is impossible for the owner to override the [`riskModule`](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/25a0c8aeaddec273c5318540059165696591ecfb/protocol-v2/src/RiskEngine.sol#L54C23-L54C33) to be any value other than what is signalled in the [`REGISTRY`](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/25a0c8aeaddec273c5318540059165696591ecfb/protocol-v2/src/RiskEngine.sol#L50C31-L50C39), since the permissionless implementation has competing write access.

Therefore, if the [`riskModule`](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/25a0c8aeaddec273c5318540059165696591ecfb/protocol-v2/src/RiskEngine.sol#L54C23-L54C33) defined in the registry is more beneficial to even just a single user compared to what has been overridden by the owner, they may simply reset it.

Conversely, if a custom [`riskModule`](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/25a0c8aeaddec273c5318540059165696591ecfb/protocol-v2/src/RiskEngine.sol#L54C23-L54C33) setting is more beneficial to users, malicious accounts can reset this as a form of griefing.

## Impact

It is not possible for the owner of the [`RiskEngine`](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/RiskEngine.sol) to administer a [`riskModule`](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/25a0c8aeaddec273c5318540059165696591ecfb/protocol-v2/src/RiskEngine.sol#L54C23-L54C33) that's different from what's currently signalled by the registry, since any user can undo this assignment.

## Code Snippet

```solidity
/// @notice Set the risk module used to store risk logic for positions
/// @dev only callable by RiskEngine owner
/// @param _riskModule the address of the risk module implementation
function setRiskModule(address _riskModule) external onlyOwner {
    riskModule = RiskModule(_riskModule);

    emit RiskModuleSet(_riskModule);
}
```

## Tool used

Manual Review

## Recommendation

Consider applying access controls to prevent the permissionless writes to the [`riskModule`](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/25a0c8aeaddec273c5318540059165696591ecfb/protocol-v2/src/RiskEngine.sol#L54C23-L54C33) if the value has been explicitly overridden by the owner.

**Comment by cawfree** [comment]
Escalate

> 1 comment(s) were left on this issue during the judging contest.
> 
> **z3s** commented:
> 
> > Low/Info; `updateFromRegistry()` has no access control is a design decision, so `setRiskModule` is a unneccessary function

Although it is correct that `updateFromRegistry` lacking access controls is indeed a valid design decision, it is also the intention of the protocol team to be able to override this functionality by exposing the `setRiskModule` function specifically for protocol administrators only.

Therefore, the issue is not that `updateFromRegistry` is permissionless, the issue is that it has **competing write access to a permissioned function**.

Consider this similar finding from Exactly where an administrator-only interface was also rendered impotent by permissionless actions:

https://github.com/sherlock-audit/2024-07-exactly-stacking-contracts-judging/issues/46

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> > 1 comment(s) were left on this issue during the judging contest.
> > 
> > **z3s** commented:
> > 
> > > Low/Info; `updateFromRegistry()` has no access control is a design decision, so `setRiskModule` is a unneccessary function
> 
> Although it is correct that `updateFromRegistry` lacking access controls is indeed a valid design decision, it is also the intention of the protocol team to be able to override this functionality by exposing the `setRiskModule` function specifically for protocol administrators only.
> 
> Therefore, the issue is not that `updateFromRegistry` is permissionless, the issue is that it has **competing write access to a permissioned function**.
> 
> Consider this similar finding from Exactly where an administrator-only interface was also rendered impotent by permissionless actions:
> 
> https://github.com/sherlock-audit/2024-07-exactly-stacking-contracts-judging/issues/46

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cawfree** [comment]
Upon further inspection, this appears to be a duplicate of #457.

**Comment by cvetanovv** [comment]
I agree it is a duplicate of #506 and #457. However, both issues will be invalid: https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/506#issuecomment-2364019668

Planning to reject the escalation and leave the issue as is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [cawfree](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/82/#issuecomment-2351809388): rejected
